<a href="https://colab.research.google.com/github/Alvaroguijarro97/ML_Group_Project/blob/main/Data_Population_Migrant_Foreign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import matplotlib.pylab as plt
import numpy as np

# Foreign Population in Germany by state

In [48]:
# Upload the "12521-0021_flat.csv" file into the notebook and set it as a dataframe
from google.colab import files
uploaded = files.upload()

Saving 12521-0021_flat.csv to 12521-0021_flat (1).csv

In [49]:
import io
foreign_data = pd.read_csv(io.BytesIO(uploaded['12521-0021_flat.csv']), encoding="windows_1258")

foreign_data.info()

foreign_data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Statistik_Code              432 non-null    int64
 1   Statistik_Label             432 non-null    object
 2   Zeit_Code                   432 non-null    object
 3   Zeit_Label                  432 non-null    object
 4   Zeit                        432 non-null    object
 5   1_Merkmal_Code              432 non-null    object
 6   1_Merkmal_Label             432 non-null    object
 7   1_Auspraegung_Code          432 non-null    int64
 8   1_Auspraegung_Label         432 non-null    object
 9   2_Merkmal_Code              432 non-null    object
 10  2_Merkmal_Label             432 non-null    object
 11  2_Auspraegung_Code          288 non-null    object
 12  2_Auspraegung_Label         432 non-null    object
 13  3_Merkmal_Code              432 non-null    object
 14  3_Merkmal_Label             432 non-null    object
 15  3_Auspraegung_Code          384 non-null    object
 16  3_Auspraegung_Label         432 non-null    object
 17  BEV027__Auslaender__Anzahl  432 non-null    int64
dtypes: int64(3), object(15)
memory usage: 60.9+ KB

,Statistik_Code,Statistik_Label,Zeit_Code,Zeit_Label,Zeit,1_Merkmal_Code,1_Merkmal_Label,1_Auspraegung_Code,1_Auspraegung_Label,2_Merkmal_Code,2_Merkmal_Label,2_Auspraegung_Code,2_Auspraegung_Label,3_Merkmal_Code,3_Merkmal_Label,3_Auspraegung_Code,3_Auspraegung_Label,BEV027__Auslaender__Anzahl
0,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,NaN,Insgesamt,998975
1,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,ST124,Belgien,1295
2,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,ST126,Dänemark,605
3,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,ST129,Frankreich,15220
4,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,8,Baden-Württemberg,GES,Geschlecht,GESM,männlich,STAAG6,Staatsangehörigkeit,ST148,Niederlande,4350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST148,Niederlande,605
428,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST151,Österreich,785
429,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST152,Polen,13210
430,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST158,Schweiz,275
431,12521,Ausländerstatistik,STAG,Stichtag,31.12.2021,DLAND,Bundesländer,16,Thüringen,GES,Geschlecht,NaN,Insgesamt,STAAG6,Staatsangehörigkeit,ST164,Tschechien,1715

In [7]:
# rename columns, cleaning data
  # renaming: "Statistik_Code"	"Statistik_Label"	"Zeit_Code"	"Zeit_Label"	"Zeit" are all the same for this table. They can be added as header/general info about the table, no need to keep them inside the table
  # renaming: 1_Auspraegung_Label = State of residence (in Germany); 2_Auspraegung_Label = Sex; 3_Auspraegung_Label = Citizenship (outside Germany); BEV027__Auslaender__Anzahl = Number of Foreigners in the state
foreign_data_renamed = foreign_data.rename(columns={"1_Auspraegung_Label": "State of residence (in Germany)", "2_Auspraegung_Label": "Sex", "3_Auspraegung_Label": "Citizenship (outside Germany)", "BEV027__Auslaender__Anzahl": "Number of Foreigners in the state"})
# filter data for rows and columns that matter in the given context
  # suggest filter: from here on, using only "insgesamt" for Sex, not distinguishing male/female
foreign_data_renamed_filtered = foreign_data_renamed.loc[foreign_data_renamed["Sex"] == "Insgesamt"]
  # filter for the renamed variables (excluding sex, as it is the same across all observations after the last step) 
foreign_data_renamed_filtered = foreign_data_renamed_filtered.filter(items=["State of residence (in Germany)", "Citizenship (outside Germany)", "Number of Foreigners in the state"])

# make observation unit "state of residence", widen "Citizenship"
foreign_data_renamed_filtered = pd.pivot(foreign_data_renamed_filtered, index = "State of residence (in Germany)", columns = "Citizenship (outside Germany)", values = "Number of Foreigners in the state")

# order columns by country_name, "insgesamt" as a final column 
foreign_data_renamed_filtered = foreign_data_renamed_filtered [["Belgien", "Dänemark", "Frankreich", "Niederlande", "Österreich", "Polen", "Schweiz", "Tschechien", "Insgesamt"]]

foreign_data_by_state = foreign_data_renamed_filtered.rename(
    columns={
        "Belgien": "Belgium",
        "Dänemark": "Denmark",
        "Frankreich": "France",
        "Niederlande": "Netherlands",
        "Österreich": "Austria",
        "Polen": "Poland", 
        "Schweiz": "Switzerland", 
        "Tschechien": "Czech Republic", 
        "Insgesamt": "Total"
        },
    index={
        "Bayern": "Bavaria",
        "Hessen": "Hesse",
        "Mecklenburg-Vorpommern": "Mecklenburg Western Pomerania",	
        "Niedersachsen": "Lower Saxony",
        "Nordrhein-Westfalen": "Northrhine-Westphalia",
        "Rheinland-Pfalz": "Rhineland Palatinate",
        "Thüringen" : "Thuringia"
        })

foreign_data_by_state

Citizenship (outside Germany),Belgium,Denmark,France,Netherlands,Austria,Poland,Switzerland,Czech Republic,Total
State of residence (in Germany),,,,,,,,,
Baden-Württemberg,2520,1245,29540,7915,26405,83870,13510,6765,1885925
Bavaria,2950,2130,23100,9855,85365,117825,7095,26395,2051505
Berlin,2540,3475,22600,7885,14025,66855,3425,2885,848400
Brandenburg,215,180,1005,1145,1405,25510,560,785,149540
Bremen,200,215,1035,1025,815,9460,265,215,140330
Hamburg,570,1530,4465,2525,3875,23310,1350,645,328375
Hesse,2635,1105,13285,8060,13280,80695,3050,4180,1163800
Mecklenburg Western Pomerania,85,170,415,840,700,15720,365,430,87410
Lower Saxony,1390,1455,4875,29745,6795,100220,2435,2225,895490
Northrhine-Westphalia,12815,2145,20575,69315,21310,220530,5335,5340,2815800
Rhineland Palatinate,2610,495,8265,6730,5210,44360,1540,1835,532230
Saarland,430,85,6790,640,1015,5780,315,290,134350
Sachsen,360,170,1830,1105,1915,22040,795,8155,244415
Sachsen-Anhalt,140,65,425,795,670,12225,265,855,127670
Schleswig-Holstein,440,7020,1780,2245,3120,29395,1110,565,286270
Thuringia,130,60,510,605,785,13210,275,1715,126270

# Population with Migrant Background in Germany

In [66]:
# Upload the "Data_Migrant_Background_Small_Comma_adapted.txt" file into the notebook and set it as a dataframe
from google.colab import files
uploaded = files.upload()

Saving Data_Migrant_Background_Small_Comma_adapted.txt to Data_Migrant_Background_Small_Comma_adapted (1).txt

In [70]:
import io
# "5 Bevölkerung 2020 nach Migrationsstatus, Ländern und Geschlecht"
# numbers in 1 000
migrant_background_data = pd.read_csv(io.BytesIO(uploaded['Data_Migrant_Background_Small_Comma_adapted.txt']), encoding="windows_1258")

migrant_background_data = migrant_background_data.T

In [63]:
# create tidy data frame from messy data from "Data_Migrant_Background_Small_Comma_adapted.txt" file
migrant_background_data_cleaned = pd.DataFrame(
    {
       "Overall Population": [81861   , 69577   , 12284   , 10976   , 12920   , 3621   , 2474   ,  674   , 1828   , 6201   , 1581   , 7857   , 17658   , 4017   ,  968   , 3995   , 2144   , 2857   , 2090   ],
     "Population without migrant background": [59976   , 48804   , 11173   , 7154   , 9493   , 2369   , 2246   ,  418   , 1199   , 3980   , 1443   , 6066   , 12137   , 2905   ,  749   , 3622   , 1949   , 2335   , 1912   ],
     "Population with migrant Background": [21885   , 20773   , 1111   , 3822   , 3427   , 1251   ,  228   ,  256   ,  630   , 2221   ,  138   , 1791   , 5521   , 1112   ,  219   ,  373   ,  194   ,  523   ,  177   ],
        "European migrant Background": [13798, 13218, 580, 2613, 2398, 751, 130, 137, 347, 1348, 77, 1064, 3433, 686, 137, 188, 92, 306, 93],
     "EU-27": [7475   ,  7100  ,  375   , 1442   , 1437   ,  356   ,  88   ,  60   ,  168   ,  696   ,  49   ,  562   , 1757   ,  369   ,  84   ,  117   ,  58   ,  171   ,  63],
     "Bulgaria": [273   ,  245   ,  27   ,  37   , 33   , 22   ,np.nan   , 9   ,np.nan   ,  40   ,np.nan   , 19   ,  54   ,  18   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan],
     "France": [247   ,  240   ,np.nan   ,  58   ,  41   ,  26   ,np.nan   ,np.nan   ,np.nan   ,  19   ,np.nan   , 10   ,  40   ,  21   , 11   ,np.nan   ,np.nan   ,np.nan   ,np.nan],
     "Greece": [467   ,  454   ,np.nan   ,  106   ,  76   , 16   ,np.nan   ,np.nan   ,np.nan   ,  39   ,np.nan   ,  28   ,  152   ,  18   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Italy": [912   ,  899   , 14   ,  262   ,  155   ,  43   ,np.nan   ,np.nan   , 13   ,  101   ,np.nan   ,  43   ,  205   ,  40   ,  25   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Croatia": [417   ,  411   ,np.nan   ,  127   ,  115   , 15   ,np.nan   ,np.nan   ,np.nan   ,  48   ,np.nan   , 14   ,  59   ,  14   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Netherlands": [255   ,  247   ,np.nan   ,  20   , 20   ,np.nan   ,np.nan   ,np.nan   ,np.nan   , 14   ,np.nan   ,  58   ,  100   , 9   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Austria": [430   ,  416   , 14   ,  65   ,  178   ,  25   ,np.nan   ,np.nan   ,np.nan   ,  29   ,np.nan   ,  20   ,  60   ,  13   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Poland": [2060   , 1919   ,  141   ,  228   ,  216   ,  111   ,  44   ,  24   ,  66   ,  178   ,  27   ,  222   ,  699   ,  102   , 14   ,  28   ,  24   ,  58   ,  19   ],
     "Portugal": [183   ,  179   ,np.nan   ,  33   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,  25   ,np.nan   ,np.nan   ,  61   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Rumania": [953   ,  911   ,  42   ,  284   ,  286   , 16   ,np.nan   ,np.nan   ,np.nan   ,  78   ,np.nan   ,  51   ,  110   ,  48   ,np.nan   , 17   ,np.nan   , 18   ,np.nan   ],
     "Spain": [256   ,  252   ,np.nan   ,  42   ,  40   , 20   ,np.nan   ,np.nan   ,np.nan   ,  32   ,np.nan   ,  27   ,  68   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Czech Republic": [217   ,  186   ,  31   ,  40   ,  69   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,  31   ,np.nan   ,np.nan   ,  22   , 8   ,np.nan   ,  15   ,np.nan   ,np.nan   ,np.nan   ],
     "Hungary": [296   ,  268   ,  28   ,  79   ,  84   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,  23   ,np.nan   , 13   ,  34   , 13   ,np.nan   ,  12   ,np.nan   ,np.nan   ,np.nan   ],
     "Further European Countries": [6323   , 6118   ,  205   , 1171   ,  961   ,  395   ,  42   ,  78   ,  179   ,  652   ,  28   ,  502   , 1675   ,  316   ,  53   ,  72   ,  33   ,  135   ,  30],
     "Bosnia and Herzegovina":  [498   ,  494   ,np.nan   ,  125   ,  138   , 18   ,np.nan   ,np.nan   ,np.nan   ,  64   ,np.nan   , 15   ,  84   ,  24   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Kosovo": [443   ,  435   ,np.nan   ,  111   ,  102   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,  33   ,np.nan   ,  36   ,  88   ,  31   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan  ],
     "Moldova": [89   ,  80   ,np.nan   , 14   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "North Macedonia": [154   ,  150   ,np.nan   ,  34   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   , 15   ,np.nan   ,np.nan   ,  56   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Russia": [ 1225   , 1143   ,  82   ,  192   ,  159   ,  62   , 14   ,  13   ,  21   ,  103   ,  12   ,  155   ,  313   ,  82   ,  17   ,  33   , 12   ,  26   , 12   ],
     "Serbia": [351   ,  342   , 9   ,  96   ,  69   , 20   ,np.nan   ,np.nan   ,np.nan   ,  46   ,np.nan   , 17   ,  64   , 11   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Turkey": [2757   , 2731   ,  27   ,  471   ,  335   ,  197   ,np.nan   ,  44   ,  94   ,  309   ,np.nan   ,  182   ,  900   ,  113   , 20   , 8   ,np.nan   ,  64   ,np.nan   ],
     "Ukraine": [325   ,  286   ,  39   ,  46   ,  55   ,  32   ,np.nan   ,np.nan   ,np.nan   ,  27   ,np.nan   ,  28   ,  60   ,  18   ,np.nan   ,  14   ,np.nan   ,np.nan   ,np.nan  ],
     "United Kingdom": [176   ,  170   ,np.nan   ,  19   , 24   , 21   ,np.nan   ,np.nan   ,np.nan   ,  18   ,np.nan   ,  25   ,  42   , 7   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ]
     }
     )

migrant_background_data_cleaned = migrant_background_data_cleaned.rename(
    index={
        0: "Germany",
        1: "West Germany and Berlin",
        2: "East Germany",
        3: "Baden-Württemberg",
        4: "Bavaria",
        5: "Berlin",
        6: "Brandenburg",
        7: "Bremen",
        8: "Hamburg",
        9: "Hesse",
        10: "Mecklenburg Western Pomerania",
        11: "Lower Saxony",
        12: "Northrhine-Westphalia",
        13: "Rhineland Palatinate",
        14: "Saarland",
        15: "Sachsen",
        16: "Sachsen-Anhalt",
        17: "Schleswig-Holstein",
        18: "Thuringia"
        }
        )

# multiply by 1000 in order to get absolute numbers and allow comparatibility across 
migrant_background_data_cleaned = migrant_background_data_cleaned.multiply(1000)

migrant_background_data_cleaned

,Overall Population,Population without migrant background,Population with migrant Background,European migrant Background,EU-27,Bulgaria,France,Greece,Italy,Croatia,...,Further European Countries,Bosnia and Herzegovina,Kosovo,Moldova,North Macedonia,Russia,Serbia,Turkey,Ukraine,United Kingdom
Germany,81861000,59976000,21885000,13798000,7475000,273000.0,247000.0,467000.0,912000.0,417000.0,...,6323000,498000.0,443000.0,89000.0,154000.0,1225000,351000.0,2757000.0,325000.0,176000.0
West Germany and Berlin,69577000,48804000,20773000,13218000,7100000,245000.0,240000.0,454000.0,899000.0,411000.0,...,6118000,494000.0,435000.0,80000.0,150000.0,1143000,342000.0,2731000.0,286000.0,170000.0
East Germany,12284000,11173000,1111000,580000,375000,27000.0,NaN,NaN,14000.0,NaN,...,205000,NaN,NaN,NaN,NaN,82000,9000.0,27000.0,39000.0,NaN
Baden-Württemberg,10976000,7154000,3822000,2613000,1442000,37000.0,58000.0,106000.0,262000.0,127000.0,...,1171000,125000.0,111000.0,14000.0,34000.0,192000,96000.0,471000.0,46000.0,19000.0
Bavaria,12920000,9493000,3427000,2398000,1437000,33000.0,41000.0,76000.0,155000.0,115000.0,...,961000,138000.0,102000.0,NaN,NaN,159000,69000.0,335000.0,55000.0,24000.0
Berlin,3621000,2369000,1251000,751000,356000,22000.0,26000.0,16000.0,43000.0,15000.0,...,395000,18000.0,NaN,NaN,NaN,62000,20000.0,197000.0,32000.0,21000.0
Brandenburg,2474000,2246000,228000,130000,88000,NaN,NaN,NaN,NaN,NaN,...,42000,NaN,NaN,NaN,NaN,14000,NaN,NaN,NaN,NaN
Bremen,674000,418000,256000,137000,60000,9000.0,NaN,NaN,NaN,NaN,...,78000,NaN,NaN,NaN,NaN,13000,NaN,44000.0,NaN,NaN
Hamburg,1828000,1199000,630000,347000,168000,NaN,NaN,NaN,13000.0,NaN,...,179000,NaN,NaN,NaN,NaN,21000,NaN,94000.0,NaN,NaN
Hesse,6201000,3980000,2221000,1348000,696000,40000.0,19000.0,39000.0,101000.0,48000.0,...,652000,64000.0,33000.0,NaN,15000.0,103000,46000.0,309000.0,27000.0,18000.0
Mecklenburg Western Pomerania,1581000,1443000,138000,77000,49000,NaN,NaN,NaN,NaN,NaN,...,28000,NaN,NaN,NaN,NaN,12000,NaN,NaN,NaN,NaN
Lower Saxony,7857000,6066000,1791000,1064000,562000,19000.0,10000.0,28000.0,43000.0,14000.0,...,502000,15000.0,36000.0,NaN,NaN,155000,17000.0,182000.0,28000.0,25000.0
Northrhine-Westphalia,17658000,12137000,5521000,3433000,1757000,54000.0,40000.0,152000.0,205000.0,59000.0,...,1675000,84000.0,88000.0,NaN,56000.0,313000,64000.0,900000.0,60000.0,42000.0
Rhineland Palatinate,4017000,2905000,1112000,686000,369000,18000.0,21000.0,18000.0,40000.0,14000.0,...,316000,24000.0,31000.0,NaN,NaN,82000,11000.0,113000.0,18000.0,7000.0
Saarland,968000,749000,219000,137000,84000,NaN,11000.0,NaN,25000.0,NaN,...,53000,NaN,NaN,NaN,NaN,17000,NaN,20000.0,NaN,NaN
Sachsen,3995000,3622000,373000,188000,117000,NaN,NaN,NaN,NaN,NaN,...,72000,NaN,NaN,NaN,NaN,33000,NaN,8000.0,14000.0,NaN
Sachsen-Anhalt,2144000,1949000,194000,92000,58000,NaN,NaN,NaN,NaN,NaN,...,33000,NaN,NaN,NaN,NaN,12000,NaN,NaN,NaN,NaN
Schleswig-Holstein,2857000,2335000,523000,306000,171000,NaN,NaN,NaN,NaN,NaN,...,135000,NaN,NaN,NaN,NaN,26000,NaN,64000.0,NaN,NaN
Thuringia,2090000,1912000,177000,93000,63000,NaN,NaN,NaN,NaN,NaN,...,30000,NaN,NaN,NaN,NaN,12000,NaN,NaN,NaN,NaN

In [64]:
# filter "migrant_background_data" down to show only states ("Länder") as rows and EU states as countries in the columns 
migrant_background_data_by_state = migrant_background_data_cleaned.iloc[3:, 5:18]

migrant_background_data_by_state

,Bulgaria,France,Greece,Italy,Croatia,Netherlands,Austria,Poland,Portugal,Rumania,Spain,Czech Republic,Hungary
Baden-Württemberg,37000.0,58000.0,106000.0,262000.0,127000.0,20000.0,65000.0,228000,33000.0,284000.0,42000.0,40000.0,79000.0
Bavaria,33000.0,41000.0,76000.0,155000.0,115000.0,20000.0,178000.0,216000,NaN,286000.0,40000.0,69000.0,84000.0
Berlin,22000.0,26000.0,16000.0,43000.0,15000.0,NaN,25000.0,111000,NaN,16000.0,20000.0,NaN,NaN
Brandenburg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44000,NaN,NaN,NaN,NaN,NaN
Bremen,9000.0,NaN,NaN,NaN,NaN,NaN,NaN,24000,NaN,NaN,NaN,NaN,NaN
Hamburg,NaN,NaN,NaN,13000.0,NaN,NaN,NaN,66000,NaN,NaN,NaN,NaN,NaN
Hesse,40000.0,19000.0,39000.0,101000.0,48000.0,14000.0,29000.0,178000,25000.0,78000.0,32000.0,31000.0,23000.0
Mecklenburg Western Pomerania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27000,NaN,NaN,NaN,NaN,NaN
Lower Saxony,19000.0,10000.0,28000.0,43000.0,14000.0,58000.0,20000.0,222000,NaN,51000.0,27000.0,NaN,13000.0
Northrhine-Westphalia,54000.0,40000.0,152000.0,205000.0,59000.0,100000.0,60000.0,699000,61000.0,110000.0,68000.0,22000.0,34000.0
Rhineland Palatinate,18000.0,21000.0,18000.0,40000.0,14000.0,9000.0,13000.0,102000,NaN,48000.0,NaN,8000.0,13000.0
Saarland,NaN,11000.0,NaN,25000.0,NaN,NaN,NaN,14000,NaN,NaN,NaN,NaN,NaN
Sachsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28000,NaN,17000.0,NaN,15000.0,12000.0
Sachsen-Anhalt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24000,NaN,NaN,NaN,NaN,NaN
Schleswig-Holstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58000,NaN,18000.0,NaN,NaN,NaN
Thuringia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19000,NaN,NaN,NaN,NaN,NaN

# General Census Data

In [74]:
# taking "migrant_background_data_cleaned", as it includes population numbers per state("Bundesland"). Filter for population number and 
census_data = migrant_background_data_cleaned.iloc[3:, :3]

census_data['Foreign Population (migrant background, no German Passport)'] = foreign_data_by_state.loc[:,"Total"]

census_data

,Overall Population,Population without migrant background,Population with migrant Background,"Foreign Population (migrant background, no German Passport)"
Baden-Württemberg,10976000,7154000,3822000,1885925
Bavaria,12920000,9493000,3427000,2051505
Berlin,3621000,2369000,1251000,848400
Brandenburg,2474000,2246000,228000,149540
Bremen,674000,418000,256000,140330
Hamburg,1828000,1199000,630000,328375
Hesse,6201000,3980000,2221000,1163800
Mecklenburg Western Pomerania,1581000,1443000,138000,87410
Lower Saxony,7857000,6066000,1791000,895490
Northrhine-Westphalia,17658000,12137000,5521000,2815800
Rhineland Palatinate,4017000,2905000,1112000,532230
Saarland,968000,749000,219000,134350
Sachsen,3995000,3622000,373000,244415
Sachsen-Anhalt,2144000,1949000,194000,127670
Schleswig-Holstein,2857000,2335000,523000,286270
Thuringia,2090000,1912000,177000,126270