<a href="https://colab.research.google.com/github/Alvaroguijarro97/ML_Group_Project/blob/main/wrangling_df_into_state_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# make sure to install "PyPDF2" via "pip install PyPDF2"
# importing required modules
import pandas as pd
import matplotlib.pylab as plt
import numpy as np

In [10]:
# take data frame with abortion scores
df_abortion_atlas = pd.DataFrame(
    {
"OVERALL TOTAL": [60, 0, 65, 61, 63, 61, 78, 48, 66, 60, 59, 64, 83, 65, 82, 84, 58, 62.5, 8, 68, 43, 91, 63.5, 77, 67, 56, 11, 62, 76, 0, 63, 14, 65, 85, 44, 59.5, 74, 81, 16, 67, 59, 58, 22, 60, 53, 66, 71, 94, 76, 54.5, 66, 89, 100],
"LEGAL STATUS OF ABORTION CARE (TOTAL SCORE)": [12, 0, 12, 9, 12, 12, 12, 9, 12, 12, 9, 12, 12, 12, 12, 12, 12, 9, 3, 9, 9, 15, 9, 12, 12, 12, 6, 12, 12, 0, 12, 3, 12, 15, 9, 9, 12, 12, 2, 9, 9, 12, 3, 12, 12, 9, 12, 15, 9, 9, 12, 15, 15],
"ACCESS (TOTAL SCORE)": [31, 0, 30, 35, 29, 30, 37, 22, 32, 32, 28, 27, 41, 31, 38, 38, 26, 32, 3, 35, 23, 44, 32, 37, 37, 21, 3, 32, 36, 0, 29, 4, 34, 41, 20, 28.5, 33, 40, 7, 33, 30, 32, 19, 29, 28, 33, 35, 44, 36, 30, 32, 43, 45],
"CLINICAL CARE AND SERVICE DELIVERY (TOTAL SCORE)": [17, 0, 20, 14, 19, 16, 22, 14, 19, 13, 19, 22, 23, 19, 27, 24, 17, 16, 2, 21, 14, 25, 15.5, 21, 14, 16, 2, 15, 21, 0, 19, 7, 16, 19, 15, 19, 19, 19, 10, 19, 17, 16, 0, 19, 13, 21, 19, 25, 21, 15.5, 19, 21, 30],
"INFORMATION AND ON-LINE INFORMATION (TOTAL SCORE)": [0, 0, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 7, 3, 5, 10, 3, 5.5, 0, 3, -3, 7, 7, 7, 4, 7, 0, 3, 7, 0, 3, 0, 3, 10, 0, 3, 10, 10, -3, 6, 3, -2, 0, 0, 0, 3, 5, 10, 10, 0, 3, 10, 10]
    }
)

df_abortion_atlas = df_abortion_atlas.rename(
    index={
        0: "Albania",
1: "Andorra",
2: "Armenia",
3: "Austria",
4: "Azerbaijan",
5: "Belarus",
6: "Belgium",
7: "Bosn.- Herziv.*",
8: "Bulgaria",
9: "Croatia",
10: "Cyprus",
11: "Czech Republic",
12: "Denmark" ,
13: "Estonia",
14: "Finland",
15: "France",
16: "Georgia",
17: "Germany",
18: "Gibraltar",
19: "Greece",
20: "Hungary",
21: "Iceland",
22: "Ireland",
23: "Isle of Man",
24: "Italy",
25: "Latvia",
26: "Liechtenstein",
27: "Lithuania",
28: "Luxembourg",
29: "Malta",
30: "Moldova",
31: "Monaco",
32: "Montenegro",
33: "Netherlands",
34: "N. Cyprus",
35: "N. Ireland",
36: "N. Macedonia",
37: "Norway",
38: "Poland",
39: "Portugal",
40: "Romania",
41: "Russia",
42: "San Marino",
43: "Serbia",
44: "Slovakia",
45: "Slovenia",
46: "Spain",
47: "Sweden",
48: "Swizerland",
49: "Turkey",
50: "Ukraine",
51: "UK (E, S & W)",
52: "Perfect score"
        }
        )

In [11]:
# take data frame with migrant background data
migrant_background_data_cleaned = pd.DataFrame(
    {
       "Overall Population": [81861   , 69577   , 12284   , 10976   , 12920   , 3621   , 2474   ,  674   , 1828   , 6201   , 1581   , 7857   , 17658   , 4017   ,  968   , 3995   , 2144   , 2857   , 2090   ],
     "Population without migrant background": [59976   , 48804   , 11173   , 7154   , 9493   , 2369   , 2246   ,  418   , 1199   , 3980   , 1443   , 6066   , 12137   , 2905   ,  749   , 3622   , 1949   , 2335   , 1912   ],
     "Population with migrant Background": [21885   , 20773   , 1111   , 3822   , 3427   , 1251   ,  228   ,  256   ,  630   , 2221   ,  138   , 1791   , 5521   , 1112   ,  219   ,  373   ,  194   ,  523   ,  177   ],
        "European migrant Background": [13798, 13218, 580, 2613, 2398, 751, 130, 137, 347, 1348, 77, 1064, 3433, 686, 137, 188, 92, 306, 93],
     "EU-27": [7475   ,  7100  ,  375   , 1442   , 1437   ,  356   ,  88   ,  60   ,  168   ,  696   ,  49   ,  562   , 1757   ,  369   ,  84   ,  117   ,  58   ,  171   ,  63],
     "Bulgaria": [273   ,  245   ,  27   ,  37   , 33   , 22   ,np.nan   , 9   ,np.nan   ,  40   ,np.nan   , 19   ,  54   ,  18   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan],
     "France": [247   ,  240   ,np.nan   ,  58   ,  41   ,  26   ,np.nan   ,np.nan   ,np.nan   ,  19   ,np.nan   , 10   ,  40   ,  21   , 11   ,np.nan   ,np.nan   ,np.nan   ,np.nan],
     "Greece": [467   ,  454   ,np.nan   ,  106   ,  76   , 16   ,np.nan   ,np.nan   ,np.nan   ,  39   ,np.nan   ,  28   ,  152   ,  18   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Italy": [912   ,  899   , 14   ,  262   ,  155   ,  43   ,np.nan   ,np.nan   , 13   ,  101   ,np.nan   ,  43   ,  205   ,  40   ,  25   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Croatia": [417   ,  411   ,np.nan   ,  127   ,  115   , 15   ,np.nan   ,np.nan   ,np.nan   ,  48   ,np.nan   , 14   ,  59   ,  14   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Netherlands": [255   ,  247   ,np.nan   ,  20   , 20   ,np.nan   ,np.nan   ,np.nan   ,np.nan   , 14   ,np.nan   ,  58   ,  100   , 9   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Austria": [430   ,  416   , 14   ,  65   ,  178   ,  25   ,np.nan   ,np.nan   ,np.nan   ,  29   ,np.nan   ,  20   ,  60   ,  13   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Poland": [2060   , 1919   ,  141   ,  228   ,  216   ,  111   ,  44   ,  24   ,  66   ,  178   ,  27   ,  222   ,  699   ,  102   , 14   ,  28   ,  24   ,  58   ,  19   ],
     "Portugal": [183   ,  179   ,np.nan   ,  33   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,  25   ,np.nan   ,np.nan   ,  61   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Romania": [953   ,  911   ,  42   ,  284   ,  286   , 16   ,np.nan   ,np.nan   ,np.nan   ,  78   ,np.nan   ,  51   ,  110   ,  48   ,np.nan   , 17   ,np.nan   , 18   ,np.nan   ],
     "Spain": [256   ,  252   ,np.nan   ,  42   ,  40   , 20   ,np.nan   ,np.nan   ,np.nan   ,  32   ,np.nan   ,  27   ,  68   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Czech Republic": [217   ,  186   ,  31   ,  40   ,  69   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,  31   ,np.nan   ,np.nan   ,  22   , 8   ,np.nan   ,  15   ,np.nan   ,np.nan   ,np.nan   ],
     "Hungary": [296   ,  268   ,  28   ,  79   ,  84   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,  23   ,np.nan   , 13   ,  34   , 13   ,np.nan   ,  12   ,np.nan   ,np.nan   ,np.nan   ],
     "Further European Countries": [6323   , 6118   ,  205   , 1171   ,  961   ,  395   ,  42   ,  78   ,  179   ,  652   ,  28   ,  502   , 1675   ,  316   ,  53   ,  72   ,  33   ,  135   ,  30],
     "Bosnia and Herzegovina":  [498   ,  494   ,np.nan   ,  125   ,  138   , 18   ,np.nan   ,np.nan   ,np.nan   ,  64   ,np.nan   , 15   ,  84   ,  24   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Kosovo": [443   ,  435   ,np.nan   ,  111   ,  102   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,  33   ,np.nan   ,  36   ,  88   ,  31   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan  ],
     "Moldova": [89   ,  80   ,np.nan   , 14   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "North Macedonia": [154   ,  150   ,np.nan   ,  34   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   , 15   ,np.nan   ,np.nan   ,  56   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Russia": [ 1225   , 1143   ,  82   ,  192   ,  159   ,  62   , 14   ,  13   ,  21   ,  103   ,  12   ,  155   ,  313   ,  82   ,  17   ,  33   , 12   ,  26   , 12   ],
     "Serbia": [351   ,  342   , 9   ,  96   ,  69   , 20   ,np.nan   ,np.nan   ,np.nan   ,  46   ,np.nan   , 17   ,  64   , 11   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ],
     "Turkey": [2757   , 2731   ,  27   ,  471   ,  335   ,  197   ,np.nan   ,  44   ,  94   ,  309   ,np.nan   ,  182   ,  900   ,  113   , 20   , 8   ,np.nan   ,  64   ,np.nan   ],
     "Ukraine": [325   ,  286   ,  39   ,  46   ,  55   ,  32   ,np.nan   ,np.nan   ,np.nan   ,  27   ,np.nan   ,  28   ,  60   ,  18   ,np.nan   ,  14   ,np.nan   ,np.nan   ,np.nan  ],
     "United Kingdom": [176   ,  170   ,np.nan   ,  19   , 24   , 21   ,np.nan   ,np.nan   ,np.nan   ,  18   ,np.nan   ,  25   ,  42   , 7   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ,np.nan   ]
     }
     )

migrant_background_data_cleaned = migrant_background_data_cleaned.rename(
    index={
        0: "Germany",
        1: "West Germany and Berlin",
        2: "East Germany",
        3: "Baden-Württemberg",
        4: "Bavaria",
        5: "Berlin",
        6: "Brandenburg",
        7: "Bremen",
        8: "Hamburg",
        9: "Hesse",
        10: "Mecklenburg Western Pomerania",
        11: "Lower Saxony",
        12: "Northrhine-Westphalia",
        13: "Rhineland Palatinate",
        14: "Saarland",
        15: "Sachsen",
        16: "Sachsen-Anhalt",
        17: "Schleswig-Holstein",
        18: "Thuringia"
        }
        )

migrant_background_data_by_state = migrant_background_data_cleaned.iloc[3:, 5:18]

In [12]:
# currently, this df (like the others created) list German states as rows and countries as columns
# ideally, we want to have three independent variables:
  # proximity to neighoubring countries
  # foreigners share within state
  # migrant background share within state
# for all three variables, we are also interested in interaction effects with abortion scores for the respective country (of origin)
# currently the columns for abortion scores would contain the same values in every row (as they are by country "Bulgaria", "France", etc.),
  # interaction effects for three vavriables and abortion scores hard to calculate in this format(?)
migrant_background_data_by_state

,Bulgaria,France,Greece,Italy,Croatia,Netherlands,Austria,Poland,Portugal,Romania,Spain,Czech Republic,Hungary
Baden-Württemberg,37.0,58.0,106.0,262.0,127.0,20.0,65.0,228,33.0,284.0,42.0,40.0,79.0
Bavaria,33.0,41.0,76.0,155.0,115.0,20.0,178.0,216,NaN,286.0,40.0,69.0,84.0
Berlin,22.0,26.0,16.0,43.0,15.0,NaN,25.0,111,NaN,16.0,20.0,NaN,NaN
Brandenburg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,NaN,NaN,NaN,NaN,NaN
Bremen,9.0,NaN,NaN,NaN,NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN
Hamburg,NaN,NaN,NaN,13.0,NaN,NaN,NaN,66,NaN,NaN,NaN,NaN,NaN
Hesse,40.0,19.0,39.0,101.0,48.0,14.0,29.0,178,25.0,78.0,32.0,31.0,23.0
Mecklenburg Western Pomerania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,NaN,NaN,NaN,NaN,NaN
Lower Saxony,19.0,10.0,28.0,43.0,14.0,58.0,20.0,222,NaN,51.0,27.0,NaN,13.0
Northrhine-Westphalia,54.0,40.0,152.0,205.0,59.0,100.0,60.0,699,61.0,110.0,68.0,22.0,34.0
Rhineland Palatinate,18.0,21.0,18.0,40.0,14.0,9.0,13.0,102,NaN,48.0,NaN,8.0,13.0
Saarland,NaN,11.0,NaN,25.0,NaN,NaN,NaN,14,NaN,NaN,NaN,NaN,NaN
Sachsen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,NaN,17.0,NaN,15.0,12.0
Sachsen-Anhalt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN
Schleswig-Holstein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,NaN,18.0,NaN,NaN,NaN
Thuringia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN

In [13]:
# wrangling example df migrant_background_data 

  # create working_version
migrant_background_data_working_version = migrant_background_data_by_state

  # create new variable state, so the respective state is not (only) in the index
migrant_background_data_working_version["state"] = ["Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Mecklenburg Western Pomerania", "Lower Saxony", "Northrhine-Westphalia", "Rhineland Palatinate", "Saarland", "Sachsen", "Sachsen-Anhalt", "Schleswig-Holstein", "Thuringia"]

  # Unpivot df from wide to long format, each observation is one state/country combination (instead of each observation a state with several countries as variables per single observation) 
migrant_background_data_working_version = pd.melt(migrant_background_data_working_version, id_vars=["state"], value_vars=["Bulgaria", "France", "Greece", "Italy", "Croatia", "Netherlands", "Austria", "Poland", "Portugal", "Romania", "Spain", "Czech Republic", "Hungary"],
        var_name = "Country", value_name = "Population with migrant background")

  # create place holder values for new column "Country_Score", that will allow to insert for each observation the corresponding abortion score for the correct country 
migrant_background_data_working_version["Country_Score"] = migrant_background_data_working_version.loc[:,"Country"]

  # sort this wrangled df so it lists for each state the respective independent variable of interest (here: population with a specific migrant background) ordered by size  
migrant_background_data_by_state_sorted = migrant_background_data_working_version.sort_values(by=["state", "Population with migrant background"])

  # in order have this order kept intact: 
    # create an object that counts in a range of one number per country 
counter = np.array([1., 2., 3., 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

    # create column for this counter called "number", creating an additional index to keep sorted order intact later on 
migrant_background_data_by_state_sorted["number"] = np.resize(counter, migrant_background_data_by_state_sorted.shape[0])

# see resulting df that has for each state/country observation the independent variable (here: population with migrant background),
# sorted by IV size, together with an index for IV size and a place holder for respective the abortion score
migrant_background_data_by_state_sorted

,state,Country,Population with migrant background,Country_Score,number
80,Baden-Württemberg,Netherlands,20.0,Netherlands,1.0
128,Baden-Württemberg,Portugal,33.0,Portugal,2.0
0,Baden-Württemberg,Bulgaria,37.0,Bulgaria,3.0
176,Baden-Württemberg,Czech Republic,40.0,Czech Republic,4.0
160,Baden-Württemberg,Spain,42.0,Spain,5.0
...,...,...,...,...,...
143,Thuringia,Portugal,NaN,Portugal,9.0
159,Thuringia,Romania,NaN,Romania,10.0
175,Thuringia,Spain,NaN,Spain,11.0
191,Thuringia,Czech Republic,NaN,Czech Republic,12.0
207,Thuringia,Hungary,NaN,Hungary,13.0

In [14]:
# IGNORE, DIFFERENT ATTEMPT: 
    # migrant_background_data_by_state['Bulgaria'] = migrant_background_data_by_state['Bulgaria'] + ', str'

    # migrant_background_data_Baden_Württemberg = migrant_background_data_by_state_sorted[migrant_background_data_by_state_sorted["state"] == "Baden-Württemberg"] 

    # migrant_background_data_Baden_Württemberg

    # migrant_background_data_Baden_Württemberg.iloc[::8, :]

In [15]:
# pivot ("long to wide") df so that each state once again is row (observation)
migrant_background_data_by_state_sorted = migrant_background_data_by_state_sorted.pivot(index='state', columns='number', values=['Population with migrant background', "Country", "Country_Score"])

# now, columns are NOT JUST countries (same for all states), but for each state (observation/row) the countries individually sorted (thus distinct per state)
  # suggested naming convention: now columns "by state", before columns "by country"
# values in each column are individual per row, interaction effects between columns can be detected   
migrant_background_data_by_state_sorted

                              Population with migrant background              \
number                                                      1.0   2.0   3.0
state
Baden-Württemberg                                           20.0  33.0  37.0
Bavaria                                                     20.0  33.0  40.0
Berlin                                                      15.0  16.0  16.0
Brandenburg                                                 44.0   NaN   NaN
Bremen                                                       9.0  24.0   NaN
Hamburg                                                     13.0  66.0   NaN
Hesse                                                       14.0  19.0  23.0
Lower Saxony                                                10.0  13.0  14.0
Mecklenburg Western Pomerania                               27.0   NaN   NaN
Northrhine-Westphalia                                       22.0  34.0  40.0
Rhineland Palatinate                                         8.0   9.0  13.0
Saarland                                                    11.0  14.0  25.0
Sachsen                                                     12.0  15.0  17.0
Sachsen-Anhalt                                              24.0   NaN   NaN
Schleswig-Holstein                                          18.0  58.0   NaN
Thuringia                                                   19.0   NaN   NaN

                                                                            \
number                         4.0   5.0   6.0   7.0    8.0    9.0    10.0
state
Baden-Württemberg              40.0  42.0  58.0  65.0   79.0  106.0  127.0
Bavaria                        41.0  69.0  76.0  84.0  115.0  155.0  178.0
Berlin                         20.0  22.0  25.0  26.0   43.0  111.0    NaN
Brandenburg                     NaN   NaN   NaN   NaN    NaN    NaN    NaN
Bremen                          NaN   NaN   NaN   NaN    NaN    NaN    NaN
Hamburg                         NaN   NaN   NaN   NaN    NaN    NaN    NaN
Hesse                          25.0  29.0  31.0  32.0   39.0   40.0   48.0
Lower Saxony                   19.0  20.0  27.0  28.0   43.0   51.0   58.0
Mecklenburg Western Pomerania   NaN   NaN   NaN   NaN    NaN    NaN    NaN
Northrhine-Westphalia          54.0  59.0  60.0  61.0   68.0  100.0  110.0
Rhineland Palatinate           13.0  14.0  18.0  18.0   21.0   40.0   48.0
Saarland                        NaN   NaN   NaN   NaN    NaN    NaN    NaN
Sachsen                        28.0   NaN   NaN   NaN    NaN    NaN    NaN
Sachsen-Anhalt                  NaN   NaN   NaN   NaN    NaN    NaN    NaN
Schleswig-Holstein              NaN   NaN   NaN   NaN    NaN    NaN    NaN
Thuringia                       NaN   NaN   NaN   NaN    NaN    NaN    NaN

                               ...   Country_Score                  \
number                         ...            4.0             5.0
state                          ...
Baden-Württemberg              ...  Czech Republic           Spain
Bavaria                        ...          France  Czech Republic
Berlin                         ...           Spain        Bulgaria
Brandenburg                    ...          Greece           Italy
Bremen                         ...          Greece           Italy
Hamburg                        ...          France          Greece
Hesse                          ...        Portugal         Austria
Lower Saxony                   ...        Bulgaria         Austria
Mecklenburg Western Pomerania  ...          Greece           Italy
Northrhine-Westphalia          ...        Bulgaria         Croatia
Rhineland Palatinate           ...         Hungary         Croatia
Saarland                       ...        Bulgaria          Greece
Sachsen                        ...          Poland        Bulgaria
Sachsen-Anhalt                 ...          Greece           Italy
Schleswig-Holstein             ...          France          Greece
Thuringia                      ...          Greece           Italy

                                                                         \
number                                   6.0          7.0          8.0
state
Baden-Württemberg                      France      Austria      Hungary
Bavaria                                Greece      Hungary      Croatia
Berlin                                Austria       France        Italy
Brandenburg                           Croatia  Netherlands      Austria
Bremen                                Croatia  Netherlands      Austria
Hamburg                               Croatia  Netherlands      Austria
Hesse                          Czech Republic        Spain       Greece
Lower Saxony                            Spain       Greece        Italy
Mecklenburg Western Pomerania         Croatia  Netherlands      Austria
Northrhine-Westphalia                 Austria     Portugal        Spain
Rhineland Palatinate                 Bulgaria       Greece       France
Saarland                              Croatia  Netherlands      Austria
Sachsen                                France       Greece        Italy
Sachsen-Anhalt                        Croatia  Netherlands      Austria
Schleswig-Holstein                      Italy      Croatia  Netherlands
Thuringia                             Croatia  Netherlands      Austria

                                                                   \
number                                9.0          10.0      11.0
state
Baden-Württemberg                   Greece      Croatia    Poland
Bavaria                              Italy      Austria    Poland
Berlin                              Poland  Netherlands  Portugal
Brandenburg                       Portugal      Romania     Spain
Bremen                            Portugal      Romania     Spain
Hamburg                           Portugal      Romania     Spain
Hesse                             Bulgaria      Croatia   Romania
Lower Saxony                       Romania  Netherlands    Poland
Mecklenburg Western Pomerania     Portugal      Romania     Spain
Northrhine-Westphalia          Netherlands      Romania    Greece
Rhineland Palatinate                 Italy      Romania    Poland
Saarland                          Portugal      Romania     Spain
Sachsen                            Croatia  Netherlands   Austria
Sachsen-Anhalt                    Portugal      Romania     Spain
Schleswig-Holstein                 Austria     Portugal     Spain
Thuringia                         Portugal      Romania     Spain


number                                   12.0            13.0
state
Baden-Württemberg                       Italy         Romania
Bavaria                               Romania        Portugal
Berlin                         Czech Republic         Hungary
Brandenburg                    Czech Republic         Hungary
Bremen                         Czech Republic         Hungary
Hamburg                        Czech Republic         Hungary
Hesse                                   Italy          Poland
Lower Saxony                         Portugal  Czech Republic
Mecklenburg Western Pomerania  Czech Republic         Hungary
Northrhine-Westphalia                   Italy          Poland
Rhineland Palatinate                 Portugal           Spain
Saarland                       Czech Republic         Hungary
Sachsen                              Portugal           Spain
Sachsen-Anhalt                 Czech Republic         Hungary
Schleswig-Holstein             Czech Republic         Hungary
Thuringia                      Czech Republic         Hungary

[16 rows x 39 columns]

In [18]:
# replace place holder country names in column Country_Score with value from the abortion atlas df
migrant_background_data_by_state_sorted["Country_Score"] = migrant_background_data_by_state_sorted["Country_Score"].replace(["Bulgaria", "Poland", "Luxembourg", "Lithuania", "France", "Greece", "Italy", "Croatia", "Netherlands", "Austria", "Portugal", "Romania", "Spain", "Czech Republic", "Hungary"],
                                                                        [df_abortion_atlas.at["Bulgaria", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Poland", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Luxembourg", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Lithuania", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["France", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Greece", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Italy", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Croatia", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Netherlands", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Austria", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Portugal", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Romania", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Spain", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Czech Republic", "ACCESS (TOTAL SCORE)"],
                                                                         df_abortion_atlas.at["Hungary", "ACCESS (TOTAL SCORE)"]])
migrant_background_data_by_state_sorted

                              Population with migrant background              \
number                                                      1.0   2.0   3.0
state
Baden-Württemberg                                           20.0  33.0  37.0
Bavaria                                                     20.0  33.0  40.0
Berlin                                                      15.0  16.0  16.0
Brandenburg                                                 44.0   NaN   NaN
Bremen                                                       9.0  24.0   NaN
Hamburg                                                     13.0  66.0   NaN
Hesse                                                       14.0  19.0  23.0
Lower Saxony                                                10.0  13.0  14.0
Mecklenburg Western Pomerania                               27.0   NaN   NaN
Northrhine-Westphalia                                       22.0  34.0  40.0
Rhineland Palatinate                                         8.0   9.0  13.0
Saarland                                                    11.0  14.0  25.0
Sachsen                                                     12.0  15.0  17.0
Sachsen-Anhalt                                              24.0   NaN   NaN
Schleswig-Holstein                                          18.0  58.0   NaN
Thuringia                                                   19.0   NaN   NaN

                                                                            \
number                         4.0   5.0   6.0   7.0    8.0    9.0    10.0
state
Baden-Württemberg              40.0  42.0  58.0  65.0   79.0  106.0  127.0
Bavaria                        41.0  69.0  76.0  84.0  115.0  155.0  178.0
Berlin                         20.0  22.0  25.0  26.0   43.0  111.0    NaN
Brandenburg                     NaN   NaN   NaN   NaN    NaN    NaN    NaN
Bremen                          NaN   NaN   NaN   NaN    NaN    NaN    NaN
Hamburg                         NaN   NaN   NaN   NaN    NaN    NaN    NaN
Hesse                          25.0  29.0  31.0  32.0   39.0   40.0   48.0
Lower Saxony                   19.0  20.0  27.0  28.0   43.0   51.0   58.0
Mecklenburg Western Pomerania   NaN   NaN   NaN   NaN    NaN    NaN    NaN
Northrhine-Westphalia          54.0  59.0  60.0  61.0   68.0  100.0  110.0
Rhineland Palatinate           13.0  14.0  18.0  18.0   21.0   40.0   48.0
Saarland                        NaN   NaN   NaN   NaN    NaN    NaN    NaN
Sachsen                        28.0   NaN   NaN   NaN    NaN    NaN    NaN
Sachsen-Anhalt                  NaN   NaN   NaN   NaN    NaN    NaN    NaN
Schleswig-Holstein              NaN   NaN   NaN   NaN    NaN    NaN    NaN
Thuringia                       NaN   NaN   NaN   NaN    NaN    NaN    NaN

                               ... Country_Score                          \
number                         ...          4.0   5.0   6.0   7.0   8.0
state                          ...
Baden-Württemberg              ...          27.0  35.0  38.0  35.0  23.0
Bavaria                        ...          38.0  27.0  35.0  23.0  32.0
Berlin                         ...          35.0  32.0  35.0  38.0  37.0
Brandenburg                    ...          35.0  37.0  32.0  41.0  35.0
Bremen                         ...          35.0  37.0  32.0  41.0  35.0
Hamburg                        ...          38.0  35.0  32.0  41.0  35.0
Hesse                          ...          33.0  35.0  27.0  35.0  35.0
Lower Saxony                   ...          32.0  35.0  35.0  35.0  37.0
Mecklenburg Western Pomerania  ...          35.0  37.0  32.0  41.0  35.0
Northrhine-Westphalia          ...          32.0  32.0  35.0  33.0  35.0
Rhineland Palatinate           ...          23.0  32.0  32.0  35.0  38.0
Saarland                       ...          32.0  35.0  32.0  41.0  35.0
Sachsen                        ...           7.0  32.0  38.0  35.0  37.0
Sachsen-Anhalt                 ...          35.0  37.0  32.0  41.0  35.0
Schleswig-Holstein             ...          38.0  35.0  37.0  32.0  41.0
Thuringia                      ...          35.0  37.0  32.0  41.0  35.0


number                         9.0   10.0  11.0  12.0  13.0
state
Baden-Württemberg              35.0  32.0   7.0  37.0  30.0
Bavaria                        37.0  35.0   7.0  30.0  33.0
Berlin                          7.0  41.0  33.0  27.0  23.0
Brandenburg                    33.0  30.0  35.0  27.0  23.0
Bremen                         33.0  30.0  35.0  27.0  23.0
Hamburg                        33.0  30.0  35.0  27.0  23.0
Hesse                          32.0  32.0  30.0  37.0   7.0
Lower Saxony                   30.0  41.0   7.0  33.0  27.0
Mecklenburg Western Pomerania  33.0  30.0  35.0  27.0  23.0
Northrhine-Westphalia          41.0  30.0  35.0  37.0   7.0
Rhineland Palatinate           37.0  30.0   7.0  33.0  35.0
Saarland                       33.0  30.0  35.0  27.0  23.0
Sachsen                        32.0  41.0  35.0  33.0  35.0
Sachsen-Anhalt                 33.0  30.0  35.0  27.0  23.0
Schleswig-Holstein             35.0  33.0  35.0  27.0  23.0
Thuringia                      33.0  30.0  35.0  27.0  23.0

[16 rows x 39 columns]